import type {
  Product,
  Order,
  Discount,
  GiftCard,
  SalesData,
  ProductPerformance,
  CustomerDetails,
  Address,
} from "@/types"

// Helper to generate random dates within a range
const randomDate = (start: Date, end: Date) => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
}

// Helper to generate random IDs
const generateId = () => Math.random().toString(36).substring(2, 10)

// Helper to generate UUID-like IDs
const generateUUID = () => {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0
    const v = c == "x" ? r : (r & 0x3) | 0x8
    return v.toString(16)
  })
}

// Updated mockProducts array with correct structure
export const mockProducts: Product[] = [
  {
    id: generateUUID(),
    barcode: "1a2b3c",
    title: "Immune Boost Herbal Tincture",
    description: "Natural herbal tincture to support immune system function with echinacea, elderberry, and astragalus",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 2999,
    inventory: 120,
    quantity: 0,
    category: "Tinctures",
    tags: ["immune", "tincture", "natural", "echinacea"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "2d4e5f",
    title: "Digestive Health Capsules",
    description: "Herbal capsules to support digestive health and gut function with ginger, fennel, and peppermint",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 3499,
    inventory: 78,
    quantity: 0,
    category: "Capsules",
    tags: ["digestive", "capsules", "gut-health", "ginger"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "3g6h7i",
    title: "Sleep Support Herbal Tea",
    description: "Calming herbal tea blend to promote restful sleep with chamomile, lavender, and passionflower",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 1899,
    inventory: 32,
    quantity: 0,
    category: "Teas",
    tags: ["sleep", "tea", "relaxation", "chamomile"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "4j8k9l",
    title: "Joint Support Salve",
    description: "Topical herbal salve for joint and muscle comfort with arnica, turmeric, and wintergreen",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 2799,
    inventory: 45,
    quantity: 0,
    category: "Topicals",
    tags: ["joint", "salve", "topical", "arnica"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "5m0n1o",
    title: "Stress Relief Herbal Extract",
    description: "Concentrated herbal extract to support stress management with ashwagandha, rhodiola, and holy basil",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 4299,
    inventory: 65,
    quantity: 0,
    category: "Extracts",
    tags: ["stress", "extract", "anxiety", "ashwagandha"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "6p2q3r",
    title: "Energy Boost Herbal Blend",
    description: "Natural energy blend with ginseng, guarana, and green tea to support vitality and focus",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 3199,
    inventory: 89,
    quantity: 0,
    category: "Capsules",
    tags: ["energy", "ginseng", "focus", "natural"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "7s4t5u",
    title: "Detox Herbal Tea",
    description: "Cleansing herbal tea blend with dandelion, milk thistle, and burdock root for natural detoxification",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 2199,
    inventory: 56,
    quantity: 0,
    category: "Teas",
    tags: ["detox", "cleanse", "dandelion", "liver"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "8v6w7x",
    title: "Heart Health Tincture",
    description: "Cardiovascular support tincture with hawthorn, garlic, and cayenne for heart health",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 3799,
    inventory: 42,
    quantity: 0,
    category: "Tinctures",
    tags: ["heart", "cardiovascular", "hawthorn", "circulation"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "9y8z0a",
    title: "Women's Balance Capsules",
    description: "Herbal support for women's hormonal balance with red clover, dong quai, and black cohosh",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 4199,
    inventory: 67,
    quantity: 0,
    category: "Capsules",
    tags: ["women", "hormonal", "balance", "red-clover"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "0b1c2d",
    title: "Respiratory Support Syrup",
    description: "Soothing herbal syrup for respiratory health with elderberry, thyme, and licorice root",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 2899,
    inventory: 38,
    quantity: 0,
    category: "Syrups",
    tags: ["respiratory", "cough", "elderberry", "soothing"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "3e4f5g",
    title: "Memory & Focus Blend",
    description: "Cognitive support blend with ginkgo biloba, bacopa, and lion's mane for mental clarity",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 4599,
    inventory: 73,
    quantity: 0,
    category: "Capsules",
    tags: ["memory", "focus", "cognitive", "ginkgo"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "6h7i8j",
    title: "Anti-Inflammatory Turmeric Blend",
    description: "Powerful anti-inflammatory blend with turmeric, ginger, and black pepper for joint health",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 3299,
    inventory: 91,
    quantity: 0,
    category: "Capsules",
    tags: ["anti-inflammatory", "turmeric", "joint", "ginger"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "9k0l1m",
    title: "Skin Health Herbal Oil",
    description: "Nourishing herbal oil blend for healthy skin with calendula, rosehip, and jojoba",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 2599,
    inventory: 54,
    quantity: 0,
    category: "Topicals",
    tags: ["skin", "oil", "calendula", "nourishing"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "2n3o4p",
    title: "Liver Support Capsules",
    description: "Liver detox and support capsules with milk thistle, dandelion, and artichoke leaf",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 3699,
    inventory: 48,
    quantity: 0,
    category: "Capsules",
    tags: ["liver", "detox", "milk-thistle", "cleanse"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUUID(),
    barcode: "5q6r7s",
    title: "Mood Support Herbal Tea",
    description: "Uplifting herbal tea blend with St. John's wort, lemon balm, and rose petals for emotional wellness",
    thumbnail: "/placeholder.svg?height=300&width=300",
    price: 2399,
    inventory: 61,
    quantity: 0,
    category: "Teas",
    tags: ["mood", "emotional", "st-johns-wort", "uplifting"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Sample customer details
const sampleCustomerDetails: CustomerDetails[] = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "555-123-4567",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "555-987-6543",
  },
  {
    firstName: "Robert",
    lastName: "Johnson",
    email: "robert.johnson@example.com",
    phone: "555-456-7890",
  },
  {
    firstName: "Sarah",
    lastName: "Williams",
    email: "sarah.williams@example.com",
    phone: "555-789-0123",
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    phone: "555-234-5678",
  },
]

// Sample addresses
const sampleAddresses: Address[] = [
  {
    firstName: "John",
    lastName: "Doe",
    address1: "123 Main St",
    city: "Anytown",
    province: "CA",
    postalCode: "12345",
    country: "USA",
    phone: "555-123-4567",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    address1: "456 Oak Ave",
    city: "Somewhere",
    province: "NY",
    postalCode: "67890",
    country: "USA",
    phone: "555-987-6543",
  },
  {
    firstName: "Robert",
    lastName: "Johnson",
    address1: "789 Pine St",
    city: "Elsewhere",
    province: "TX",
    postalCode: "54321",
    country: "USA",
    phone: "555-456-7890",
  },
  {
    firstName: "Sarah",
    lastName: "Williams",
    address1: "321 Elm St",
    city: "Nowhere",
    province: "FL",
    postalCode: "09876",
    country: "USA",
    phone: "555-789-0123",
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    address1: "654 Maple Ave",
    city: "Someplace",
    province: "WA",
    postalCode: "13579",
    country: "USA",
    phone: "555-234-5678",
  },
]

// Update the mockOrders to include herbal medicine products
export const mockOrders: Order[] = [
  {
    id: "order_01",
    customerDetails: sampleCustomerDetails[0],
    items: [
      {
        id: "item_01",
        title: "Immune Boost Herbal Tincture - 30ml",
        quantity: 2,
        unitPrice: 2999,
        thumbnail: "/placeholder.svg?height=300&width=300",
        variant: {
          id: "var_01",
          title: "30ml",
        },
      },
    ],
    status: "delivered",
    paymentStatus: "captured",
    fulfillmentStatus: "fulfilled",
    total: 7498,
    subtotal: 5998,
    shippingTotal: 1500,
    discountTotal: 0,
    taxTotal: 0,
    shippingAddress: sampleAddresses[0],
    billingAddress: sampleAddresses[0],
    createdAt: randomDate(new Date(2023, 0, 1), new Date()),
    updatedAt: randomDate(new Date(2023, 0, 1), new Date()),
  },
  {
    id: "order_02",
    customerDetails: sampleCustomerDetails[1],
    items: [
      {
        id: "item_02",
        title: "Digestive Health Capsules - 60 Capsules",
        quantity: 1,
        unitPrice: 3499,
        thumbnail: "/placeholder.svg?height=300&width=300",
        variant: {
          id: "var_03",
          title: "60 Capsules",
        },
      },
      {
        id: "item_03",
        title: "Stress Relief Herbal Extract - 30ml Dropper",
        quantity: 1,
        unitPrice: 4299,
        thumbnail: "/placeholder.svg?height=300&width=300",
        variant: {
          id: "var_11",
          title: "30ml Dropper",
        },
      },
    ],
    status: "shipped",
    paymentStatus: "captured",
    fulfillmentStatus: "shipped",
    total: 9298,
    subtotal: 7798,
    shippingTotal: 1500,
    discountTotal: 0,
    taxTotal: 0,
    shippingAddress: sampleAddresses[1],
    billingAddress: sampleAddresses[1],
    createdAt: randomDate(new Date(2023, 0, 1), new Date()),
    updatedAt: randomDate(new Date(2023, 0, 1), new Date()),
  },
  {
    id: "order_03",
    customerDetails: sampleCustomerDetails[2],
    items: [
      {
        id: "item_04",
        title: "Sleep Support Herbal Tea - Loose Leaf - 50g",
        quantity: 1,
        unitPrice: 1899,
        thumbnail: "/placeholder.svg?height=300&width=300",
        variant: {
          id: "var_05",
          title: "Loose Leaf - 50g",
        },
      },
    ],
    status: "processing",
    paymentStatus: "captured",
    fulfillmentStatus: "not_fulfilled",
    total: 3399,
    subtotal: 1899,
    shippingTotal: 1500,
    discountTotal: 0,
    taxTotal: 0,
    shippingAddress: sampleAddresses[2],
    billingAddress: sampleAddresses[2],
    createdAt: randomDate(new Date(2023, 0, 1), new Date()),
    updatedAt: randomDate(new Date(2023, 0, 1), new Date()),
  },
  {
    id: "order_04",
    customerDetails: sampleCustomerDetails[3],
    items: [
      {
        id: "item_05",
        title: "Joint Support Salve - Regular - 2oz",
        quantity: 1,
        unitPrice: 2799,
        thumbnail: "/placeholder.svg?height=300&width=300",
        variant: {
          id: "var_07",
          title: "Regular - 2oz",
        },
      },
      {
        id: "item_06",
        title: "Immune Boost Herbal Tincture - 60ml",
        quantity: 2,
        unitPrice: 2999,
        thumbnail: "/placeholder.svg?height=300&width=300",
        variant: {
          id: "var_02",
          title: "60ml",
        },
      },
    ],
    status: "pending",
    paymentStatus: "awaiting",
    fulfillmentStatus: "not_fulfilled",
    total: 10297,
    subtotal: 8797,
    shippingTotal: 1500,
    discountTotal: 0,
    taxTotal: 0,
    shippingAddress: sampleAddresses[3],
    billingAddress: sampleAddresses[3],
    createdAt: randomDate(new Date(2023, 0, 1), new Date()),
    updatedAt: randomDate(new Date(2023, 0, 1), new Date()),
  },
  {
    id: "order_05",
    customerDetails: sampleCustomerDetails[4],
    items: [
      {
        id: "item_07",
        title: "Stress Relief Herbal Extract - 60ml Dropper",
        quantity: 2,
        unitPrice: 4299,
        thumbnail: "/placeholder.svg?height=300&width=300",
        variant: {
          id: "var_12",
          title: "60ml Dropper",
        },
      },
    ],
    status: "canceled",
    paymentStatus: "canceled",
    fulfillmentStatus: "canceled",
    total: 10098,
    subtotal: 8598,
    shippingTotal: 1500,
    discountTotal: 0,
    taxTotal: 0,
    shippingAddress: sampleAddresses[4],
    billingAddress: sampleAddresses[4],
    createdAt: randomDate(new Date(2023, 0, 1), new Date()),
    updatedAt: randomDate(new Date(2023, 0, 1), new Date()),
  },
]

// Mock Discounts
export const mockDiscounts: Discount[] = [
  {
    id: "disc_01",
    code: "SUMMER20",
    description: "Summer sale 20% off",
    type: "percentage",
    value: 20,
    usageLimit: 100,
    usageCount: 45,
    startsAt: new Date(2023, 5, 1), // June 1, 2023
    endsAt: new Date(2023, 7, 31), // August 31, 2023
    isActive: true,
    conditions: {
      minSubtotal: 50,
    },
    createdAt: new Date(2023, 4, 15),
    updatedAt: new Date(2023, 4, 15),
  },
  {
    id: "disc_02",
    code: "FREESHIP",
    description: "Free shipping on all orders",
    type: "free_shipping",
    value: 0,
    usageLimit: 200,
    usageCount: 120,
    startsAt: new Date(2023, 0, 1),
    isActive: true,
    createdAt: new Date(2022, 11, 15),
    updatedAt: new Date(2022, 11, 15),
  },
  {
    id: "disc_03",
    code: "WELCOME10",
    description: "$10 off your first order",
    type: "fixed_amount",
    value: 10,
    usageLimit: 1000,
    usageCount: 358,
    startsAt: new Date(2023, 0, 1),
    isActive: true,
    conditions: {
      minSubtotal: 25,
    },
    createdAt: new Date(2022, 11, 1),
    updatedAt: new Date(2022, 11, 1),
  },
]

// Mock Gift Cards
export const mockGiftCards: GiftCard[] = [
  {
    id: "gift_01",
    code: "GIFT-1234-5678",
    value: 50,
    balance: 50,
    isDisabled: false,
    createdAt: new Date(2023, 1, 15),
    updatedAt: new Date(2023, 1, 15),
  },
  {
    id: "gift_02",
    code: "GIFT-8765-4321",
    value: 100,
    balance: 75.5,
    isDisabled: false,
    createdAt: new Date(2023, 2, 10),
    updatedAt: new Date(2023, 2, 10),
  },
  {
    id: "gift_03",
    code: "GIFT-9876-5432",
    value: 25,
    balance: 0,
    isDisabled: true,
    createdAt: new Date(2023, 0, 5),
    updatedAt: new Date(2023, 0, 5),
  },
]

// Mock Analytics Data
export const mockSalesData: SalesData[] = [
  { date: "2023-01", revenue: 12500, orders: 125 },
  { date: "2023-02", revenue: 15000, orders: 150 },
  { date: "2023-03", revenue: 18500, orders: 185 },
  { date: "2023-04", revenue: 22000, orders: 220 },
  { date: "2023-05", revenue: 20000, orders: 200 },
  { date: "2023-06", revenue: 25000, orders: 250 },
  { date: "2023-07", revenue: 30000, orders: 300 },
  { date: "2023-08", revenue: 27500, orders: 275 },
  { date: "2023-09", revenue: 32000, orders: 320 },
  { date: "2023-10", revenue: 35000, orders: 350 },
  { date: "2023-11", revenue: 40000, orders: 400 },
  { date: "2023-12", revenue: 50000, orders: 500 },
]

// Update the mockProductPerformance to match the new herbal medicine products
export const mockProductPerformance: ProductPerformance[] = [
  { id: "prod_01", title: "Immune Boost Herbal Tincture", sales: 350, revenue: 10496.5 },
  { id: "prod_02", title: "Digestive Health Capsules", sales: 200, revenue: 6998.0 },
  { id: "prod_03", title: "Sleep Support Herbal Tea", sales: 120, revenue: 2278.8 },
  { id: "prod_04", title: "Joint Support Salve", sales: 85, revenue: 2379.15 },
  { id: "prod_05", title: "Stress Relief Herbal Extract", sales: 175, revenue: 7523.25 },
]
